[project]
name = "pdf-merger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "markdownify>=1.1.0",
    "pdf2docx>=0.5.8",
    "pypdf2>=3.0.1",
]
